# Generated by Django 3.1 on 2020-08-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_auto_20200823_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaiasource',
            name='rv_template_teff',
            field=models.FloatField(null=True),
        ),
    ]
